version: 2

models:
  - name: hub_crypto
    columns:
      - name: CRYPTO_HK
        tests:
          - unique
          - not_null

  - name: sat_crypto_market_metrics
    columns:
      - name: CRYPTO_HK
        tests:
          - not_null